### ISSUE TITLE
error during use in a spring boot application with spring-zeebe-starter

### ISSUE THREAD

**Issue by paranoiasystem** [camunda-community-hub/camunda-operate-client-java#7]
Hi, i'm developing an application with spring boot. I'm using spring-zeebe-starter library, if I install only this library without modify anything and I try to run the app. I receive this exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'zeebeClientLifecycle' defined in io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [io.camunda.zeebe.spring.client.lifecycle.ZeebeClientLifecycle] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@4d7e1886]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.5.jar:2.7.5]
	at com.paranoiasystem.myapp.MyApplication.main(MyApplication.java:32) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.7.5.jar:2.7.5]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [io.camunda.zeebe.spring.client.lifecycle.ZeebeClientLifecycle] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@4d7e1886]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:232) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:210) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:149) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:305) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1116) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.3.23.jar:5.3.23]
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/camunda/zeebe/client/api/command/ModifyProcessInstanceCommandStep1
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3434) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2536) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467) ~[spring-core-5.3.23.jar:5.3.23]
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.camunda.zeebe.client.api.command.ModifyProcessInstanceCommandStep1
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	... 29 common frames omitted
```

this is the dependencies I use in my maven file:

```
<dependency>
    <groupId>io.camunda</groupId>
    <artifactId>spring-zeebe-starter</artifactId>
    <version>8.1.1</version>
</dependency>
...
<dependency>
    <groupId>io.camunda</groupId>
    <artifactId>camunda-operate-client-java</artifactId>
    <version>1.3.1</version>
</dependency>
```

**Comment by chDame** [comment]
Hi @paranoiasystem,

This issue seems related to zeebe spring client and not to operate client, no ?

**Comment by paranoiasystem** [comment]
this issue happen only if I install this library in my project. without it, with only spring zeebe starter I have no issue and all works gracefully. IDK why this two libraries generate this issue

**Comment by paranoiasystem** [comment]
@chDame this issue is possible releted to differences in the dependencies?
 https://github.com/camunda-community-hub/spring-zeebe/blob/master/pom.xml#L24 

https://github.com/camunda-community-hub/camunda-operate-client-java/blob/main/build.gradle#L19

**Comment by chDame** [comment]
Hi @paranoiasystem,

I'll check. I don't promise to come back with something before monday morning but I'll try!

**Comment by chDame** [comment]
Hi @paranoiasystem,

Could you check if version 1.3.2 solves your problem ?

**Comment by paranoiasystem** [comment]
Hi @chDame ,

> Hi @paranoiasystem,
> 
> Could you try excluding the zeebe-client-java dependecy from the operate client dependency in your project and see if it solves your error ?

removing this from dependencies the project start without any exception
```
<dependency>
    <groupId>io.camunda</groupId>
    <artifactId>spring-zeebe-starter</artifactId>
    <version>8.1.1</version>
</dependency>
```

> Hi @paranoiasystem,
> 
> Could you check if version 1.3.3 solves your problem ?

I can't download it, only 1.3.1 is present on maven
https://mvnrepository.com/artifact/io.camunda/camunda-operate-client-java

**Comment by chDame** [comment]
Hi @paranoiasystem,

You should better look at maven central :
https://repo.maven.apache.org/maven2/io/camunda/camunda-operate-client-java/1.3.3/

If you change the dependancy, maven will get it for you.

**Comment by paranoiasystem** [comment]
Hi @chDame, the issue persist with version 1.3.3.
The issue not appear if I remove the decorator @EnableZeebeClient but I need to use this for start my zeebe workers.
Something doesnt work properly, but I think this is really strange... I dont understand how this two library with different scopes go in conflict

**Comment by chDame** [comment]
Hi @paranoiasystem,

I'm not able to reproduce your issue. You can have a look at a community project that is using the same configuration and running fine:
https://github.com/camunda-community-hub/camunda-8-lowcode-ui-template

Could you share your repo with me?

**Comment by paranoiasystem** [comment]
I have modified my pom.xml like the project you have linked me. Now the project start correctly. The changes:

```
<?xml version="1.0" encoding="UTF-8"?>
    ....
    <properties>
        ...
        <spring-zeebe.version>8.1.1</spring-zeebe.version>
        <zeebe.version>8.1.1</zeebe.version>
    </properties>

    <dependencies>
        ...
        <dependency>
            <groupId>io.camunda</groupId>
            <artifactId>zeebe-client-java</artifactId>
            <version>${zeebe.version}</version>
        </dependency>
        <dependency>
            <groupId>io.camunda</groupId>
            <artifactId>spring-zeebe-starter</artifactId>
            <version>${spring-zeebe.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.camunda/camunda-operate-client-java -->
        <dependency>
            <groupId>io.camunda</groupId>
            <artifactId>camunda-operate-client-java</artifactId>
            <version>1.3.3</version>
        </dependency>
        ...
    </dependencies>
    ...
```

but now I receive this issue when I try to authenticate to my operate 


```
java.lang.NullPointerException: Cannot invoke "org.apache.hc.core5.http.Header.getValue()" because the return value of "org.apache.hc.client5.http.impl.classic.CloseableHttpResponse.getHeader(String)" is null
	at io.camunda.operate.auth.SimpleAuthentication.authenticate(SimpleAuthentication.java:49) ~[camunda-operate-client-java-1.3.3.jar:na]
	at io.camunda.operate.CamundaOperateClient$Builder.build(CamundaOperateClient.java:247) ~[camunda-operate-client-java-1.3.3.jar:na]
	at com.myapp.myapp.application.rest.PurchaseProcessController.popUpOpened(PurchaseProcessController.java:73) ~[classes/:na]
...
```

**Comment by chDame** [comment]
great, I'll open another issue to manage the nullpointer in the simple auth
